### ISSUE TITLE
Add in IPFS

### ISSUE THREAD

**Issue by nolim1t** [lncm/pi-factory#159]
Add in IPFS container into the docker compose.

This falls under the same philosophy of self-sovereignity, and where the more boxes that are deployed the more they should support each other. 

We won't be pinning any files yet, but would like to be able to have our website hosted on ipfs so that its constantly available and we will be decentralized at the very core of things.

Also later on we can do interesting stuff like host the website behind an .onion service

**Comment by AnotherDroog** [comment]
I’ll be using IPFS to distribute the blockchain snapshots we publish

Letting boxes then pin it and help sharing it would be in line with our aim of strengthening the network

Those who do not want to participate in sharing (possibly because of high cost volume metered internet or extremely low bandwidth) can turn it off in the dashboard

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nolim1t** [comment]
Lets hold on this for now
