### ISSUE TITLE
Make sure the tor uri updating script is more robust

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/pi-factory#92]

**Comment by nolim1t** [comment]
What’s the current result and expected?

**Comment by AnotherDroog** [comment]
There’s a remaining issue with tor uri not being written to lnd.conf if an existing config is detected

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nolim1t** [comment]
it probably isn't because the script relies on certain items to be present in the lnd.conf file to be written in.

I currently look for the presence of:

```
; externalip=
```
and then replace it with the tor uri (and uncomment it)

lnd is also a bit picky on the positioning of where certain items are as well so we can't just append it.

comments/suggestions for this problem is open

**Comment by AnotherDroog** [comment]
I'll come up with some python to edit the lnd file safely
